### ISSUE TITLE
NUC detects a display only on start-up

### ISSUE THREAD

**Issue by yoshimalucky** [ROBOTIS-GIT/ROBOTIS-OP3#10]
NUC can not detect display after power-on.

**Comment by ROBOTIS-Kayman** [comment]
We already knew this issue, but we couldn't find a solution yet.

**Comment by ROBOTIS-zerom** [comment]
The problem is a Linux Mint issue. We have to wait for the Linux Mint to fix the issue.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
