### ISSUE TITLE
Calculating relative positition and center of mass in op3 

### ISSUE THREAD

**Issue by hadyan14** [ROBOTIS-GIT/ROBOTIS-OP3#22]
op3_link_data_[6]->relative_position_ = robotis_framework::getTransitionXYZ(0.0, 0.09, 0.0);
op3_link_data_[6]->center_of_mass_ = robotis_framework::getTransitionXYZ(0.000, 0.073, 0.000);

How op3 calculate relative position and center of mass? where is the refrence position has taken?

**Comment by s-changhyun** [comment]
You can refer the information about the relative position and center of mass from URDF file (op3_description in OP3-Common).

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
