### ISSUE TITLE
Timer Thread Error

### ISSUE THREAD

**Issue by haritsahm** [ROBOTIS-GIT/ROBOTIS-OP3#23]
i got this error every time i launch op3_manager. what is wrong? 

![screenshot from 2017-11-12 23-13-09](https://user-images.githubusercontent.com/26606913/32700926-150929e4-c7ff-11e7-947b-5fc47d4dc490.png)

**Comment by ROBOTIS-Kayman** [comment]
I thing it's a priority problem.

I recommand you to set like below. (cf : [PC setting](https://github.com/ROBOTIS-GIT/ROBOTIS-Documents/wiki/OP3-Manual-Installation#22-pc-setting))
```
$ sudo bash -c 'echo "@robotis - rtprio 99" > /etc/security/limits.d/robotis-rtprio.conf'
```

**Comment by haritsahm** [comment]
thanks a lot!
