### ISSUE TITLE
Installing Continuous Integration for OP3 and Thormang3

### ISSUE THREAD

**Issue by yoshimalucky** [ROBOTIS-GIT/ROBOTIS-OP3#25]
Because we have no CI (continuous integration) tools, this type of issues happens:
https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-Tools/issues/3

Do we have any plan to use Jenkins or Travis?

For maintaining a humanoid robot software tools, this is a good example repository:
https://github.com/jsk-ros-pkg/jsk_common

**Comment by robotpilot** [comment]
@yoshimalucky 

We applied Travis CI of ROS Industrial CI to our 118 packages.
Thank you for making a good suggestion. :+1:
