### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by arixrobotics** [ROBOTIS-GIT/ROBOTIS-OP3#37]
Is there any examples for programming the OP3 in Python?
I just need a head start to continue exploring.

**Comment by ROBOTIS-Kayman** [comment]
Sorry for your inconvenience. 
But we don't have any python example for ROBOTIS-OP3.

If we make a python example, we will let you know.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
