### ISSUE TITLE
Magnetometer

### ISSUE THREAD

**Issue by arixrobotics** [ROBOTIS-GIT/ROBOTIS-OP3#38]
I see that the OpenCR has a built-in magnetometer (as well as accelerometer and gyro). How can I get the magnetometer data from OP3's ROS API?

**Comment by ROBOTIS-Kayman** [comment]
Although OpenCR contains a magnetometer sensor, OpenCR firmware for OP3 does not provide the magnetometer sensor value because there is a large error in the sensor value due to the surrounding motors in OP3.

**Comment by arixrobotics** [comment]
OK understand. Thank you.
