### ISSUE TITLE
Error First Bulk Read

### ISSUE THREAD

**Issue by haritsahm** [ROBOTIS-GIT/ROBOTIS-OP3#41]
I can't start the manager every time i add the opencr as sensor because i got this first bulk read fail.
but if i disable the opencr in op.robot, everything works

![error_sync](https://user-images.githubusercontent.com/26606913/40795452-554bf138-652c-11e8-91b0-d60ff03ea66e.png)

**Comment by ROBOTIS-Kayman** [comment]
I can't figure it out what went wrong.

Would you give me some extra information like .robot file?
What protocol version of MX-28 and MX-64 do you use?

**Comment by robotpilot** [comment]
his issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by haritsahm** [comment]
sorry i was busy, i would like to reopen this issue, this is my setup and opencr debug 
![opencr](https://user-images.githubusercontent.com/26606913/41188070-3fc7b812-6be2-11e8-82be-295916112ad7.png)

![setup](https://user-images.githubusercontent.com/26606913/41188076-5285d880-6be2-11e8-8658-5071b9f5c698.png)

**Comment by ROBOTIS-zerom** [comment]
In ROBOTIS Framework, only one protocol can be used for one port.

Change the MX-28 and MX-64 firmware to 2.0. 
1. Download R+ Manger 2.0 from here : http://en.robotis.com/service/downloadpage.php?ca_id=10 
2. Recovery the MX-28 and MX-64 firmware. : http://emanual.robotis.com/docs/en/software/rplus2/manager/#firmware-recovery

then all devices will use protocol 2.0

MX-28 (2.0) manual : http://emanual.robotis.com/docs/en/dxl/mx/mx-28-2/
MX-64 (2.0) manual : http://emanual.robotis.com/docs/en/dxl/mx/mx-64-2/

**Comment by haritsahm** [comment]
oh okay i will try it later! i thought it could use multiple protocol

**Comment by robotpilot** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.

**Comment by wiseenu** [comment]
i have same problem with error first bulk read. this my pict of the device
![Screenshot at 2022-10-27 17-53-10](https://user-images.githubusercontent.com/77100078/198266491-d26a395b-9d0d-478d-ba1a-644227b08f65.png)
