### ISSUE TITLE
Bring_Up Failed

### ISSUE THREAD

**Issue by idrobotiskidslab** [ROBOTIS-GIT/ROBOTIS-OP3#45]
please help me. Why should I do ? Thank You
![screenshot_2018-06-30_15-24-47](https://user-images.githubusercontent.com/31875768/42122573-c9e24740-7c7e-11e8-84d3-9f0e7f9a4b57.png)

**Comment by ROBOTIS-Kayman** [comment]
Did you install `octomap` package and related packages?
```
$ sudo apt-get install ros-kinetic-map-server
$ sudo apt-get install ros-kinetic-humanoid-nav-msgs
$ sudo apt-get install ros-kinetic-nav-msgs
$ sudo apt-get install ros-kinetic-octomap
$ sudo apt-get install ros-kinetic-octomap-msgs
$ sudo apt-get install ros-kinetic-octomap-ros
$ sudo apt-get install ros-kinetic-octomap-server
```

Please refer to [e-manual](http://emanual.robotis.com/docs/en/platform/op3/recovery/#installing-ros-packages-for-robotis-op3).

**Comment by idrobotiskidslab** [comment]
thank you for your reply.
I have install that related packages.
after I type `git checkout -b kinetic` in sbpl directory and then catkin_make has been success.
But when I launch Bring_up, I get Error again like this
![screenshot_2018-07-02_13-49-56](https://user-images.githubusercontent.com/31875768/42149362-0effadcc-7e00-11e8-857b-225394dd0ffa.png)

**Comment by ROBOTIS-Kayman** [comment]
I think there is a problem with the right arm.
Check the actuators at right shoulder pitch(ID 1) and right shoulder roll(ID 3) using [dynamixel manager](http://emanual.robotis.com/docs/en/software/rplus2/manager/) or [dynamixel workbench](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#introduction).

If some problem has found, follow the AS process.

**Comment by idrobotiskidslab** [comment]
How about with the error **camera.yaml not found** ?

**Comment by ROBOTIS-Kayman** [comment]
This error occurs because the camera calibration is missing.
Please refer to [camera_calibration](http://wiki.ros.org/camera_calibration) and follow the instruction.

**Comment by idrobotiskidslab** [comment]
Thank you, I will try it later.
Hopefully can be solved. 
I will report to you.
