### ISSUE TITLE
Wiring Manual for the OP3

### ISSUE THREAD

**Issue by ferri69** [ROBOTIS-GIT/ROBOTIS-OP3#52]
Hello,
 
do you have an „Wiring Manual“ for the OP3.
I don´t find anything.
If you may have a few pictures for me, this would help me a lot.
(Open CR, Intel NUC....)
 
Thanks for your help

**Comment by ROBOTIS-Kayman** [comment]
Hello, @ ferri69

Sorry for late reply.
There is no wiring documentation at this time.

We will soon make a manual and release it.
Please wait.

I attached some images for you.
![image](https://user-images.githubusercontent.com/16040148/47409854-00eb6980-d79f-11e8-9262-91f0778ec503.png)
![image](https://user-images.githubusercontent.com/16040148/47409867-08ab0e00-d79f-11e8-97a7-ed16f4c6e744.png)
![image](https://user-images.githubusercontent.com/16040148/47409886-0cd72b80-d79f-11e8-8328-e5f77c47821d.png)

**Comment by ROBOTIS-Kayman** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
