### ISSUE TITLE
Sudden power on / off in OpenCR broke NUC

### ISSUE THREAD

**Issue by yoshimalucky** [ROBOTIS-GIT/ROBOTIS-OP3#55]
We broke two NUC.

First time, NUC was broken out when our OP3 ran out the battery and shut down.

Second time, it happened when I accidentally plugged in the battery. In this case, the OpenCR board was ON, so it was powered immediately when the battery was connected.

Therefore, OpenCR seems to be weak for power management under unexpected sudden electric change.

How can we solve it? This problem will be very critical because some users try to put an expensive SBC such as Xavier.

**Comment by ROBOTIS-Kayman** [comment]
Could you send this issue using issue tracker of intranet?
