### ISSUE TITLE
Actuators ID connect to controller openCR and Interface U2D2

### ISSUE THREAD

**Issue by ferri69** [ROBOTIS-GIT/ROBOTIS-OP3#59]
![op3](https://user-images.githubusercontent.com/11034313/50729262-239ee480-1137-11e9-8a76-820f1dff7ca5.gif)

Hello,

how must I connect the actuators (servo) with the controller and the Interface U2D2?
Second question: Do I need a U2D2 power hub?

Thank you so much for your help

**Comment by ROBOTIS-Kayman** [comment]
Hi,

1. communication map
It's not exactly same with Robotis-OP3, but I think you can understand how to connect between the actuators after looking the below image.
![image](https://user-images.githubusercontent.com/16040148/50877382-eecfad80-1414-11e9-9970-0079d1531825.png)


2. U2D2 power hub
You don't need to use U2D2 power hub. OpenCR acts like that. you have to download a firmware for using in Robotis-OP3.([link](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#op3))

**Comment by ferri69** [comment]
Hello,

thank you so much for your help.  To your screenshot, it must be this: **JST_4P_EXT_5Port_Board**.
Where can I order the three following items: **JST_4P_EXT_5Port_Board**, **OP3_GPIO_Board** and **OP3_LED-AMP_Board**?

Thanks so much for your patience!

**Comment by ROBOTIS-Kayman** [comment]
Hi, 

I'm sorry but we don't sell them separately.
I think you have to make your own boards using the schematic.

Regard,
Kayman

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
