### ISSUE TITLE
Can not subscribe any topics from a remote PC w/o modifying /etc/hosts

### ISSUE THREAD

**Issue by yoshimalucky** [ROBOTIS-GIT/ROBOTIS-OP3#6]
Wi-Fi: ROBOTIS-OP-Share
$ROS_MASTER_URI = http://10.42.0.1:11311
$ROS_IP = 10.42.0.155
$ROS_HOSTNAME = 10.42.0.155

Then, I have to add this line in /etc/hosts:
10.42.0.1 robotis-op3

Without this setting, a remote PC can not communicate with a robot.

**Comment by ROBOTIS-Kayman** [comment]
Thank you for your support.
To solve this problem, user need to add the hostname(robotis-op3) in /etc/hosts of remote pc like the way you said, or modify the script of robotis-op3 as below.

1. Connect to ROBOTIS-OP3   

2. Open the script which run automatically the robot  in your favorite editor.
```$ sudo xed /usr/sbin/OP3-demo-start```  

3. Midify like below
 - from ```export ROS_HOSTNAME=$(hostname)``` 
 - to ```export ROS_HOSTNAME=10.42.0.1```

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
