### ISSUE TITLE
question about auto-fall recovery

### ISSUE THREAD

**Issue by yuan0623** [ROBOTIS-GIT/ROBOTIS-OP3#67]
Hi, I have a simple question, does OP3 has the ability to recover itself from falling on ground, in other word, once the OP3 falls on the ground, can it automatically stand up? I didn't find anything in the manual about that.

**Comment by ROBOTIS-Kayman** [comment]
Hi,

OPENCR on OP3 has a gyro and acceleration sensor. 
We use this value to check that the robot has fallen in the OP3 soccer demo. 
If it falls, it will take action for getting up. 
Please refer to source code.
 - [check for falls](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-Demo/blob/77d76182b39c8752388bda48d484cad5f9fedf70/op3_demo/src/soccer/soccer_demo.cpp#L438)
 - [action to get up](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-Demo/blob/77d76182b39c8752388bda48d484cad5f9fedf70/op3_demo/src/soccer/soccer_demo.cpp#L585)

Regards, 
Kayman

**Comment by yuan0623** [comment]
Thanks for your fast reply!
I see, we only need to publish a integer to `/robotis/action/page_num`, but is there a motion index list? I didn't see any in the source code. I'm not familiar with c++, I'm going to use Python to publish it. 
I really have no idea about how much is the `is_grass_ ? GetUpFront + ForGrass : GetUpFront` and `is_grass_ ? GetUpBack + ForGrass : GetUpBack`

**Comment by yuan0623** [comment]
thank you so much! I think I figured it out!
