### ISSUE TITLE
question about optimal parameter for turning left and right, side-walking in op3_walking_module

### ISSUE THREAD

**Issue by yuan0623** [ROBOTIS-GIT/ROBOTIS-OP3#69]
Hi
My project require the robot to turn at the fixed position (or almost fixed position) as well as side-walking . I try to use `op3_walking_module` to set the yaw angle to do it. However, it behaves really bad. The feet step on each other and the robot is not able to stabilize itself.  I see the video that OP3 is totally capable of turning and side walking, May I ask is there any place that I can get the parameters to do the turning and side-walking? 
Thanks in advance!!
Best
Yuan

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Please refer to following links. 
you can find the appropriate parameters in trial and error.
- How to tune walking parameters : [gui for walking tuner](http://emanual.robotis.com/docs/en/platform/op3/tutorials/#how-to-use-walking-tuner).
- walking parameters : [op3_walking_module](http://emanual.robotis.com/docs/en/platform/op3/robotis_ros_packages/#op3_walking_module)

Regards,
Kayman

**Comment by ROBOTIS-Kayman** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
