### ISSUE TITLE
op3 camera

### ISSUE THREAD

**Issue by xxchenchen** [ROBOTIS-GIT/ROBOTIS-OP3#73]
Hi
How can we run the camera module in gazebo? Is it possible to generate a environment using the op3 camera in gazebo? Thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi,
you can use the camera in gazebo.
1. gazebo
```
$ roslaunch op3_gazebo robotis_world.launch
```

2. op3_manager for gazebo
```
$ roslaunch op3_manager op3_gazebo.launch
```

3. display in rviz
```
$ roslaunch op3_description op3_display.launch
```

![image](https://user-images.githubusercontent.com/16040148/64305266-c3b05480-cfc9-11e9-99db-6865f56225f8.png)
![image](https://user-images.githubusercontent.com/16040148/64305274-c90d9f00-cfc9-11e9-86c4-a384fd4981ea.png)

**Comment by xxchenchen** [comment]
Thanks for your answer.

**Comment by ahmaddidiks** [comment]
I did roslaunch op3_description op3_display.launch, but got some orrors. I've installed joint-state-publisher-gui but I got this,
[WARN] [1600796056.614672]: The 'use_gui' parameter was specified, which is deprecated.  We'll attempt to find and run the GUI, but if this fails you should install the 'joint_state_publisher_gui' package instead and run that.  This backwards compatibility option will be removed in Noetic.
