### ISSUE TITLE
op3 arm joint torque.

### ISSUE THREAD

**Issue by xxchenchen** [ROBOTIS-GIT/ROBOTIS-OP3#74]
Hi,

How can we obtain torque values relating to the arm joints of robotis-op3?

could you please write me 2-3 lines of code?

Thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi, 

There is no torque in x series. you can read the current only. 
If you want to obtain the present current. I suggest 2 ways to get it.

1. using robotis_framework : refer to [thormang_p_manager](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-P-MPC/tree/master/thormang3_p_manager) and [thormang3_alarm_module](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-P-MPC/tree/master/thormang3_alarm_module)
  - change `robot_model` in manager
  - read the present current in process function of motion_module or sensor_module.

2. using dynamixel_sdk : refer to [sdk e-manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_read_write_protocol_2_0/#cpp-read-write-protocol-20)
```cpp
#include "dynamixel_sdk.h"
using namespace dynamixel;

const int BAUD_RATE = 2000000;
const double PROTOCOL_VERSION = 2.0;
const int DEFAULT_DXL_ID = 1;
const int CURRENT_CTRL_TABLE = 126;

PortHandler *port_handler = (PortHandler *) PortHandler::getPortHandler(""/dev/ttyUSB0");
port_handler->setBaudRate(BAUD_RATE);
PacketHandler *packet_handler = PacketHandler::getPacketHandler(PROTOCOL_VERSION);
uint16_t current = 0;
// port handler, dynamixel id, control table id
packet_handler->read2ByteTxRx(port_handler, DEFAULT_DXL_ID , CURRENT_CTRL_TABLE , &current);

```

Regards,
Kayman

**Comment by xxchenchen** [comment]
Thanks for your answer.

**Comment by xxchenchen** [comment]
Hİ,

we did it. However, when we reads the current values, manager cancels or we cant control by keyboard the op3.

Why? Could you please say it? thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Can you tell me more details?
Which of the above two methods did you use?
Attach a terminal log image for the problem situation.

Regards,
Kayman

**Comment by xxchenchen** [comment]
Hi,
We use the second method. We control the robot by keyboard. The robot grasp an object. We want to obtain force/torque/current knowledge.
![image](https://user-images.githubusercontent.com/48223944/66191196-71308980-e696-11e9-9f4d-ad79c11242a6.png)
![image](https://user-images.githubusercontent.com/48223944/66191209-75f53d80-e696-11e9-8272-5625f6c3eefe.png)

**Comment by xxchenchen** [comment]
Are you there?

**Comment by ROBOTIS-Kayman** [comment]
I'm sorry I'm late.

If you are using robotis_framework in op3_manager to control OP3, you can't use the second method.
Only one program can control OP3 at a time. If you use op3_manager, you should use the first method.

Edit `op3_manager/config/OP3.robot` and add` present_current` to `BULK READ ITEMS`.

In the `process` function of your MotionModule class, read and use the following:
```
       std :: string present_current_name = dxl-> present_current_item _-> item_name_;
       uint16_t present_current_data = dxl-> dxl_state _-> bulk_read_table_ [present_current_name];
       int16_t data = present_current_data;
```

Please refer to Thormang Code([robot file](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-P-MPC/blob/master/thormang3_p_manager/config/THORMANG3_P.robot), [alarm_module](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-P-MPC/blob/52e64a08d4a759c2eb93530b25d9a1bd10a58442/thormang3_alarm_module/src/alarm_module.cpp#L145)).

Regards, 
Kayman

**Comment by xxchenchen** [comment]
Many thanks for reply. Just now we will try it.

**Comment by xxchenchen** [comment]
Hi,
We receive error. We need to the other lines also: 
      
![Screenshot from 2019-10-18 09-46-51](https://user-images.githubusercontent.com/48223944/67072215-0c445b80-f18d-11e9-9e3f-cd706e9c7c38.png)
std :: string present_current_name = dxl-> present_current_item _-> item_name_;
       uint16_t present_current_data = dxl-> dxl_state _-> bulk_read_table_ [present_current_name];
       int16_t data = present_current_data;

Could you please say them
? Many thanks

**Comment by xxchenchen** [comment]
Please answer it.

**Comment by ROBOTIS-Kayman** [comment]
Please refer to [Alarm_module](https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-P-MPC/blob/52e64a08d4a759c2eb93530b25d9a1bd10a58442/thormang3_alarm_module/src/alarm_module.cpp#L145) of THORMANG3.
Code from line 145 to line 165 of `process` function is related to getting present current.

**Comment by xxchenchen** [comment]
We couldn't do it. Unable to cope with different mistakes. Thanks

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
