### ISSUE TITLE
How can we obtain force values

### ISSUE THREAD

**Issue by xxchenchen** [ROBOTIS-GIT/ROBOTIS-OP3#75]
Hi,

How can we obtain force values relating to the arm joints of robotis-op3?

Is it possible?  We see lines relating to force in manager.
Do you have  lines of code to measure force.

Thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi,

There is no way to obtain the force value in ROBOTIS-OP3.
There is no way to help. sorry.

Regards,
Kayman

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
