### ISSUE TITLE
we want to send some joint positions calculated in the python file to real OP3.

### ISSUE THREAD

**Issue by xxchenchen** [ROBOTIS-GIT/ROBOTIS-OP3#76]
Hi,
We sent some data to the python file from robot. We connected C++ and python.
Now we want to send some joint positions calculated in the python file to real OP3. (C++ from python)
Do you have some code lines?  is it possible? Could you please help me?
Thanks previously

**Comment by ROBOTIS-Kayman** [comment]
Hi,

I didn't develop ROBOTIS-OP3 in python.
I can not help you about this. 
I think you should use ROS system. (message, service, etc.)

Regards,
Kayman

**Comment by xxchenchen** [comment]
Thanks
