### ISSUE TITLE
Now we want to do both walk and transport a object.

### ISSUE THREAD

**Issue by xxchenchen** [ROBOTIS-GIT/ROBOTIS-OP3#77]
Hi Kayman,
We can run the robot. We can capture objects. Now we want to do both together. How to walk and carry objects together. Let grasp the object and let us move it and leave it somewhere else. Could you please a little information about this? Thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi,

If you use 'op3_manager', you can control the upper and lower body of robotis-op3 separately.
Please refer to this issue(#40).

And if you use other package to control the upper body of robotis-op3 to capture the objects, you can merge the system by creating a motion module for the upper body. refer to the [e-manual](http://emanual.robotis.com/docs/en/software/robotis_framework_packages/tutorials/#creating-new-motion-module).

Regards,
Kayman

**Comment by xxchenchen** [comment]
Many thanks Kayman. We will try it.
