### ISSUE TITLE
Forse Sensor

### ISSUE THREAD

**Issue by Nara0731** [ROBOTIS-GIT/ROBOTIS-OP3#79]
I look up the Document where force sensor has been mounted at the feet.

And I donot find the module of calculating ZMP from forse sensor.

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Robotis-op3 has no force sensor.
op1 and 2 have it. Please refer to the [documentation](http://emanual.robotis.com/docs/en/platform/op/development/#fsr) for that.

Regards,
Kayman

**Comment by Nara0731** [comment]
Thank you Best regards------------------ 原始邮件 ------------------
发件人: "Kayman"<notifications@github.com>
发送时间: 2019年11月11日(星期一) 上午9:55
收件人: "ROBOTIS-GIT/ROBOTIS-OP3"<ROBOTIS-OP3@noreply.github.com>;
抄送: "Nara0731"<281183720@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ROBOTIS-GIT/ROBOTIS-OP3] Forse Sensor (#79)



Hi,
 
Robotis-op3 has no force sensor.
 op1 and 2 have it. Please refer to the documentation for that.
 
Regards,
 Kayman
 
&mdash;
