### ISSUE TITLE
op3 synchronize motion with bluetooth data

### ISSUE THREAD

**Issue by waktep** [ROBOTIS-GIT/ROBOTIS-OP3#80]
I want to use the OP3 robot as a dancing robot, for transmitting song data using Bluetooth, how to stream songs via Bluetooth and when Bluetooth receives data, the robot will dance

**Comment by ROBOTIS-Kayman** [comment]
Hi,

We do not support the example program on Bluetooth. The user needs to develop about it.
I'm sorry to say that.

Regards,
Kayman

**Comment by waktep** [comment]
but is there any chance to code or command the ROS to be co-operating with bluetooth as the data reciever??

**Comment by ROBOTIS-Kayman** [comment]
Sorry. We have no experience with it.

Regards,
Kayman

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
