### ISSUE TITLE
get position and orientation

### ISSUE THREAD

**Issue by Jiangyancao** [ROBOTIS-GIT/ROBOTIS-OP3#82]
Hi,
We want to get the base position and pose as well as the orientation of different joints when the robot is walking. How can we obtain these values relating to the robotis-op3?
I'm a newcomer to the ROS. Could you give me some suggestions or help?
Thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Run the visualization launch file and you will get tf(position and orientation) for every link.
Refer to these links.
- [op3 visualization](http://emanual.robotis.com/docs/en/platform/op3/tutorials/#visualization)
- [ros tf2](http://wiki.ros.org/tf2)

Regards,
Kayman

**Comment by Jiangyancao** [comment]
ok, I think I know what should I do. Thank you!
