### ISSUE TITLE
can I directly control the torque of the joints?

### ISSUE THREAD

**Issue by yuan0623** [ROBOTIS-GIT/ROBOTIS-OP3#83]
Hi, may I know if there is a way to directly control the torque of the joints? In our dynamic model, the input is torque rather than position. Thus, we need to command torque to the joint. However, I didn't find such a way to do it. Looking forward to your response!

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Sorry, there is no way to control the torque of the joints.
If you want, you have to develop the software using Dynamixel SDK.
  - [Github](https://github.com/ROBOTIS-GIT/DynamixelSDK)
  - [E-manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_read_write_protocol_2_0/#cpp-protocol-20)

Regards,
Kayman

**Comment by fuad99** [comment]
Maybe you can try using Dynamixel Workbench application to control each Dynamixel

**Comment by yuan0623** [comment]
> Hi,
> 
> Sorry, there is no way to control the torque of the joints.
> If you want, you have to develop the software using Dynamixel SDK.
> 
> * [Github](https://github.com/ROBOTIS-GIT/DynamixelSDK)
> * [E-manual](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_read_write_protocol_2_0/#cpp-protocol-20)
> 
> Regards,
> Kayman

thank you sooooo much!

**Comment by yuan0623** [comment]
> Maybe you can try using Dynamixel Workbench application to control each Dynamixel

thank you, bro!
