### ISSUE TITLE
Walking program

### ISSUE THREAD

**Issue by fuad99** [ROBOTIS-GIT/ROBOTIS-OP3#88]
can i make own walking program using kinematics algorithm?

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Sorry for the late response.
Yes, you can make the walking program.
If you use our [framework](http://emanual.robotis.com/docs/en/software/robotis_framework_packages/), you can make other walking module like [op3_walking_module](http://emanual.robotis.com/docs/en/platform/op3/robotis_ros_packages/#op3_walking_module) and [op3_online_walking_module](http://emanual.robotis.com/docs/en/platform/op3/robotis_ros_packages/#op3_online_walking_module). and we also provide ROS Package(op3_kinematics_dynamics) for kinematics.
- source code 
  - [op3_walking_module](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/tree/master/op3_walking_module)
  - [op3_online_walking_module](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/tree/master/op3_online_walking_module)
  - [op3_kinematics_dynamics](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/tree/master/op3_kinematics_dynamics)

If you don't want to use our framework, you should make walking program using [DYNAMIXEL SDK](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/overview/)

Regards,
Kayman

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
