### ISSUE TITLE
line detection for sprint

### ISSUE THREAD

**Issue by farhanc4kra** [ROBOTIS-GIT/ROBOTIS-OP3#89]
is there a code to detect lines for sprint?thanks

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Sorry, we are not providing a code for deteting lines.
You should develop your own program for that.

Regards,
Kayman

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
