### ISSUE TITLE
3.5mm jack as input

### ISSUE THREAD

**Issue by waktep** [ROBOTIS-GIT/ROBOTIS-OP3#90]
Hi, how to add a mic on jack 3.5
I have tried it but it can't be detected, is the jack is only as output?

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Sorry for the late replay.
3.5mm jack is used for the OP3's speaker, so even if the jack is connected, it does not work normally.
How about using a mic of camera?

Regards,
Kayman

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
