### ISSUE TITLE
walking code

### ISSUE THREAD

**Issue by AbbasJ93** [ROBOTIS-GIT/ROBOTIS-OP3#91]
Hello there are explanatory for walking codes?
thank you

**Comment by ROBOTIS-Kayman** [comment]
Hi, 

Sorry for the late replay.
There is no explanatory of source code.
It should be understood by the user using function names and comments.

Regards,
Kayman

**Comment by AbbasJ93** [comment]
thank you

**Comment by AbbasJ93** [comment]
ThanksOn Mar 12, 2020 11:08, Kayman <notifications@github.com> wrote:
Hi,
Sorry for the late replay.
There is no explanatory of source code.
It should be understood by the user using function names and comments.
Regards,
Kayman
