### ISSUE TITLE
CAD files for OP3 are missing

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/ROBOTIS-OP3#92]
Hi, please let me know where I can download the CAD files for OP3. I cannot find the files on the download site.

**Comment by ROBOTIS-Kayman** [comment]
Hi,

Sorry for the late replay.
You can find it in the [emanual](http://emanual.robotis.com/docs/en/platform/op3/hardware/#hardware)

Regards,
Kayman

**Comment by robotiscustomer** [comment]
Thanks Kayman. I tried it already but I cannot move the body parts of the model nor take apart individual components. Can you provide another model that can do these?
