### ISSUE TITLE
op3_walking_module

### ISSUE THREAD

**Issue by AbbasJ93** [ROBOTIS-GIT/ROBOTIS-OP3#93]
hi
Which linear inverted pendulum or cart-table model did you use to write the op3_walking_module?
thank you

**Comment by ROBOTIS-Kayman** [comment]
Hi,

OP3 has two walking algorithms, one of witch uses a linear inverted pendulum model.
Please refer to the source code.
 - [op3_online_walking_module/src/walking_control.cpp](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/blob/b2d35a1f545e3db6bb196f4b649dcbc6303e0efb/op3_online_walking_module/src/walking_control.cpp#L887)

Regards,
Kayman

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
