### ISSUE TITLE
How long does a fully charged OP3 last?

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/ROBOTIS-OP3#96]
Hi, how long can the OP3 function after the battery is fully charged?

**Comment by ROBOTIS-Will** [comment]
@robotiscustomer 
Hi, I'm sorry about the late response on this issue.
Usually the battery lasts about 10 ~ 15 minutes, but it is heavily depends on the motion and operation.
Thank you.

**Comment by robotiscustomer** [comment]
@ROBOTIS-Will  
Thank you
