### ISSUE TITLE
Can Ichange OpenCR1.0 with Opencm9.04?

### ISSUE THREAD

**Issue by ahmaddidiks** [ROBOTIS-GIT/ROBOTIS-OP3#99]
because my opencr1.0 has RMA damage and it's need about two months for repairing by robotis. Can I use OP3 framwork to build humnaoid robot eith Opencm9.04 for subcontroller?

**Comment by ROBOTIS-Will** [comment]
Hi @ahmaddidiks,
I'm sorry about the late response.
The OpenCM9.04 does not have IMU and power supply feature to replace the OpenCR1.0, therefore it is difficult to use it as OP3 subcontroller.
Thank you.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't any recent activity. Please feel free to reopen when necessary.
